# Generated by Django 3.1.6 on 2021-02-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_text', models.CharField(max_length=5000)),
                ('blog_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date1')),
            ],
        ),
    ]
