# Generated by Django 3.1.6 on 2021-02-10 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20210210_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 7, 18, 58, 11136, tzinfo=utc)),
        ),
    ]
