# Generated by Django 3.1.6 on 2021-02-11 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_auto_20210211_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='uncategorized', max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 7, 22, 42, 305216, tzinfo=utc)),
        ),
    ]
